### ISSUE TITLE
Implementação inicial da parte de gerenciamento de usuarios

### ISSUE THREAD

**Issue by ElexandroTorres** [ElexandroTorres/Gerencia-Biblioteca#3]
Implementação inicial da parte de gerenciamento de usuarios

Fazer a lista inicial, mostrando os usuarios, um botão para adicionar um novo usuarios que leva para a tela de cadastro e a opção de clicar em algum usuario para ir para sua tela de detalhes.

Implementar o básico do click longo para deletar um usuario futuramente.

**Comment by viniciussslima** [comment]
Na tela de gerencia usuarios, teremos uma lista de usuarios com algumas informações. Como nome, numero de livros emprestados e numero de livros que estão emprestados atualmente. Podendo ter até uma pontuação de reputação.
